model:
    arch: frrnB
data:
    dataset: ropridgeone
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /data0/qilei_chen/old_alien/AI_EYE_IMGS/ROP_DATASET_with_label/9LESIONS
training:
    train_iters: 85000
    batch_size: 1
    n_workers: 1
    val_interval: 500
    print_interval: 25
    optimizer:
        name: 'sgd'
        lr: 0.000025
    loss:
        name: 'cross_entropy'
        size_average: False
    l_rate: 0.000025
    lr_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_ropridgeone_best_model.pkl
    visdom: False
